---
kind: pipeline
name: publish

steps:
- name: build
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  environment:
    DOCKER_IMAGE:
      from_secret: docker_image
  commands:
  - docker build gui -t $DOCKER_IMAGE

- name: push
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  environment:
    DOCKER_IMAGE:
      from_secret: docker_image
    DOCKER_REGISTRY:
      from_secret: docker_registry
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  commands:
  - docker login $DOCKER_REGISTRY --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  - docker push $DOCKER_IMAGE

- name: prune
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker image prune -f

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

---
kind: pipeline
type: ssh
name: staging

server:
  host:
    from_secret: staging_host
  user:
    from_secret: staging_username
  ssh_key:
    from_secret: staging_ssh_key

clone:
  disable: true

steps:
- name: pull
  environment:
    DOCKER_IMAGE:
      from_secret: docker_image
    DOCKER_CONTAINER:
      from_secret: docker_container
  commands:
  - docker pull $DOCKER_IMAGE

- name: stop
  environment:
    DOCKER_CONTAINER:
      from_secret: docker_container
  commands:
  - docker stop $DOCKER_CONTAINER || echo skipping...

- name: load
  environment:
    DOCKER_IMAGE:
      from_secret: docker_image
    DOCKER_CONTAINER:
      from_secret: docker_container
    APP_ENV:
      from_secret: app_env
    APP_URL:
      from_secret: app_url
    APP_HOST:
      from_secret: app_host
  commands:
  - docker run --name $DOCKER_CONTAINER --rm --detach --network staging -e $APP_ENV -e $APP_URL -e $APP_HOST $DOCKER_IMAGE

- name: prune
  commands:
  - docker image prune -f

depends_on:
- publish
