version: "3.4"

services:
  php:
    image: ${DOCKER_IMAGE_PHP:-pkg.miris.design/albumin/php:latest}
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
      - app_bootstrap:/srv/app/bootstrap
      - app_storage:/srv/app/storage
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-15}&charset=${POSTGRES_CHARSET:-utf8}

  caddy:
    image: ${DOCKER_IMAGE_CADDY:-pkg.miris.design/albumin/caddy:latest}
    depends_on:
      - php
    environment:
      SERVER_NAME: ${SERVER_NAME:-:80}
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
    expose:
      - 80
      - 443

  database:
    image: postgres:${POSTGRES_VERSION:-15}
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_VERSION: ${POSTGRES_VERSION:-15}
      POSTGRES_CHARSET: ${POSTGRES_CHARSET:-utf8}
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  app_bootstrap:
  app_storage:
  php_socket:
  caddy_data:
  caddy_config:
  database_data:
