#!/bin/bash

echo "**** initialise files ****"

if [ ! -s /app/www/.env ]; then
    su abc -s /bin/bash -c 'cat /app/www/.env.example > /app/www/.env'
    su abc -s /bin/bash -c 'php /app/www/artisan key:generate --force'
fi

if [ ! -f /app/www/database/database.sqlite ]; then
    su abc -s /bin/bash -c 'touch /app/www/database/database.sqlite'
fi
